#+title: Options in Capital Budgeting Analyses
#+author: Matt Brigida, Ph.D.
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup


The mechanics of capital budgeting decisions are correctly taught in corporate finance courses, but often the spirit of the process is missed.  In general, we want to accept projects.  If you are not accepting projects, then your business is not growing.  This may be fine from a purely academic perspective, but in practice management is under pressure to grow.

So should we accept negative NPV project, or somehow use more /rosy/ estimates in our calculations?  Absolutely not.  But then how can we grow the business while simultaneously maximizing shareholder wealth?  One way is to recognize, and value, the options that accepting a project may provide.


Remember, *option values are always positive*.


* A Brief History of Options

After 1973, once we had a coherent model of an option's price, we began to employ the model to value many different types of options (real and financial) embedded in contracts. For example, there are options in mortgage contracts and callable bonds.

Here we are concerned with /real/ options that are afforded by capital budgeting decisions. 


* /Strategic/ Options

** Example: 


* Option to Expand/Abandon/Wait


